title: "solarone0"
description: "solarone0의 개인 블로그."
url: "https://solarone0.github.io"
baseurl: ""
google_analytics: "G-7964S4Z1K5"
author: "solarone0"
lang: "ko"

permalink: /:year/:month/:day/:title/

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - README.md
  - PLAN.md
  - posts
  - scripts
  - package.json
  - package-lock.json
